version: '3.7'

services:
   curriculumvitae:
    image: curriculum-vitae
    build:
      context: .
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"